# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5a1ab282c743d22216482c6c0f313771105dea1912651fa0a960443c93dc791746d9bd518ca997c7d88f2b3c7bf479817aa3f9df9479604245899e463b6a1a1e

test:
  secret_key_base: 03a445bc61a18ab083c767197f4ba1ba33a808b48c5ad7223e0358a5091d5ed2110854288f276c6b88e128f14fd1775c424e6db5380dfef47b3ecbcf7326b1a2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
